# REQUIRED VARIABLES

variable "stage" {
  description = "The stage of development (e.g., test, dev, staging, prod)."
  type        = string

  validation {
    condition     = can(regex("^(test|dev|stagin|prod)$", var.stage))
    error_message = "Stage must be one of the following: test, dev, staging, prod."
  }
}

variable "purpose" {
  description = "A short description about the purpose of the created resource."
  type        = string
  default     = null

  validation {
    condition     = can(regex("^([a-zA-Z0-9-_]*)$", var.purpose))
    error_message = "Only the characters [a-zA-Z0-9-_] are allowed."
  }
}

variable "owner" {
  description = "Enable versioning on the S3 bucket. Set to true to enable."
  type        = string
  default     = null

  validation {
    condition     = length(var.owner) >= 3
    error_message = "The owner name must be at least three characters long."
  }
}

# CUSTOM VARIABLES

variable "versioning" {
  description = "Enable versioning on the bucket."
  type        = bool
  default     = false
}

variable "force_name" {
  description = "Force a specific name for the S3 bucket. If not provided, the name is autogenerated."
  type        = string
  default     = ""
}

variable "public" {
  description = "Make the S3 bucket public. Must be true for static website hosting."
  type        = bool
  default     = false
}

variable "force_destroy" {
  description = "Allow the destruction of the S3 bucket even if it contains objects."
  type        = bool
  default     = true
}

variable "static_website" {
  description = "Configure the S3 bucket to host a static website."
  type        = bool
  default     = false
}